server:
  port: 6004

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kf521/kankan-work.git
          username: 1468664360@qq.com
          password: ksf521..
          label: dev

  application:
    name: kankan-config



